#!/bin/bash

cd lib;

CC_ANDROID_ARM64="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android30-clang";
CFLAGS_ANDROID="--sysroot=$NDK_ROOT/toolchains/llvm/prebuilt/darwin-x86_64/sysroot";

CMD_SHARED_LIB="go build -buildmode=c-shared -o"

FILENAME=native-prover.so

# Builds for Android
echo "Building Android: ARM"
env GOOS=android GOARCH=arm64 CGO_ENABLED=1 CC=$CC_ANDROID_ARM64 CGO_FLAGS=$CFLAGS_ANDROID $CMD_SHARED_LIB $FILENAME && echo "Done."

