#!/bin/bash

CC_ANDROID_AMD64="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android30-clang";
CC_ANDROID_ARM64="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android30-clang";
CFLAGS_ANDROID="--sysroot=$NDK_ROOT/toolchains/llvm/prebuilt/darwin-x86_64/sysroot";

FILENAME=native-prover.a

# Build for Desktop
env GOARCH=amd64 go build -o src/desktop/amd64/$FILENAME;

# Builds for iOS
# env GOOS=ios GOARCH=amd64 go build -o src/ios/amd64/$FILENAME;
# env GOOS=ios GOARCH=arm64 go build -o src/ios/arm64/$FILENAME;

# # Builds for Android
env GOOS=android GOARCH=amd64 CGO_ENABLED=1 CC=$CC_ANDROID_AMD64 CGO_FLAGS=$CFLAGS_ANDROID go build -o src/android/amd64/$FILENAME;
env GOOS=android GOARCH=arm64 CGO_ENABLED=1 CC=$CC_ANDROID_ARM64 CGO_FLAGS=$CFLAGS_ANDROID go build -o src/android/arm64/$FILENAME;
